### ISSUE TITLE
When no Business Hours is added, null shows up on a View

### ISSUE THREAD

**Issue by rafaehlers** [katzwebservices/Gravity-Forms-Business-Hours#11]
![gv-business-hours-bug](https://user-images.githubusercontent.com/1222472/51058436-e8d1fc00-15cf-11e9-89ba-2577d1a32777.png)

Tested on BH 2.1.2

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/991397300387768/991497796581866)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/747871211/18450/

**Comment by soulseekah** [comment]
Not only on a View, but also in the Gravity Forms backend. I suspect both cases will be solved.

![image](https://user-images.githubusercontent.com/685880/51073187-36a53d80-167e-11e9-9aab-1ce3b26ac6b7.png)

**Comment by soulseekah** [comment]
Yep, fixed, tested. See if you can test some more and we can release a bugfix.

**Comment by rafaehlers** [comment]
@soulseekah the develop branch or your commit simply prevents all Business Hours data from displaying on the View.

**Comment by zackkatz** [comment]
I’ll fix tomorrow @rafaehlers

**Comment by soulseekah** [comment]
Sorry, missed the content return :( refixed.
