### ISSUE TITLE
Can't change field title

### ISSUE THREAD

**Issue by zackkatz** [katzwebservices/Gravity-Forms-Business-Hours#6]
2) after adding the field to gravity form, if I am changing text from "business hours" to something else... It doesn't save.. it revert back to "business hours" . How can I fix that ..

https://secure.helpscout.net/conversation/524175613/13374/

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/991397300387768/991498772937274)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/605497066/15540/
